#:kivy 1.10.0

<MainWidget>:
    size_hint: 1., 1.
    rows: 3

    GridLayout:
        size_hint: 1., .2
        cols:3
        Button:
            text: "See"
        Button:
            text: "You"
        Button:
            text: "Later"

    GridLayout:
        size_hint: 1., .6
        
    GridLayout:
        cols:2
        size_hint: 1., .2
        Button:
            text: "Hello"
        Button:
            text: "World"

