#:kivy 1.10.0

<MainWidget>:
    GridLayout:
        width: 800
        height: 100
        cols:2
        #pos: 0, 10
        position: 0, 100
        Button:
            text: "Hello"
        Button:
            text: "World"

    GridLayout:
        width: 800
        height: 100
        cols:3
        pos: 0, 500
        position: 0, 100
        Button:
            text: "See"
        Button:
            text: "You"
        Button:
            text: "Later"
