#!/usr/bin/env python3 

# date: 2020.01.02
# ???

import tkinter as tk
import tkinter.scrolledtext as st
import datetime

# --- functions ---

def on_click():
    text['state'] = 'normal'
    text.insert('end', str(datetime.datetime.now()) + '\n')
    text['state'] = 'disabled'
    
# --- main ---

root = tk.Tk()

text = st.ScrolledText(root, state='disabled')
text.pack()

button = tk.Button(root, text='ADD', command=on_click)
button.pack()

root.mainloop()   
